### ISSUE TITLE
How to distribute the scripts?

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/Swinject-CodeGeneration#1]
We can use CocoaPods as Apple platform dependency management, Homebrew as Mac's package manager, or RubyGems because the scripts are written in Ruby.

Which one is good for our case?

**Comment by ddengler** [comment]
My Opinion on this:

### Rubygems

Pros:
- simple
- scripts written in ruby (as @yoichitgy already mentioned)
- can be versioned with an app repo (Gemfile)

Cons:
- does not allow us to define Swinject dependency from Gemfile

### Cocoapods

Pros:
- properly versioned in Podfile
- does allow us to define Swinject dependency from podspec
- also resolves version conflicts

Cons:
- a lot going on in this space: Carthage, Swift Package Manager

### Homebrew

Pros:
- no idea what the benefit of this would be

Cons:
- cannot be managed as an individual dependency within a repo (really hate this about Swiftgen in a Carthage based repo)

Personally I would lean towards Rubygems. Cocoapods and possibly others could be added later on. @Lutzifer You opinion?

**Comment by Lutzifer** [comment]
I would try to keep the distribution ways of swinject and swinject-CG in sync, i.e. Cocoapods and Carthage afaics.

**Comment by Lutzifer** [comment]
So, thinking about it, I personally would start it with cocoapods, for the pros specified by @ddengler

**Comment by ddengler** [comment]
@Lutzifer fine with me. @yoichitgy your opinion on this?

**Comment by yoichitgy** [comment]
@ddengler thanks for the summary with pros and cons. I thought RubyGems or Homebrew were good before I read your comment, but now I think CocoaPods is good to specify dependency to Swinject.

I think we can support Carthage too like a lot of people install [jspahrsummers/xcconfigs](https://github.com/jspahrsummers/xcconfigs). Example `Cartfile` is here: https://github.com/Swinject/Swinject/blob/master/Cartfile.private

Installed locations are different. If a user installs the scripts with Carthage, they go under `Carthage/Checkouts/Swinject-CodeGeneration` directory. With CocoaPods, `Pods/Swinject-CodeGeneration` directory. We need to document the usage with the different paths.

@Lutzifer, @ddengler: Is supporting both CocoaPods and Carthage ok for you too?

**Comment by ddengler** [comment]
@yoichitgy fine with me. Not a Carthage expert though – yet :)

**Comment by ddengler** [comment]
Closed in favor of #11 and #10 then.
