### ISSUE TITLE
GitFlow

### ISSUE THREAD

**Issue by Lutzifer** [Swinject/Swinject-CodeGeneration#18]
Can we use a gitflow workflow with master/dev/feature?

**Comment by yoichitgy** [comment]
I think simple GitHub Flow is better here.

**Comment by Lutzifer** [comment]
ok, that means branch -> PR against master?

**Comment by yoichitgy** [comment]
Yes, like that. With using `rebase`, commit history (merged branches) becomes simple.

https://guides.github.com/introduction/flow/
https://github.com/Swinject/Swinject/network
