### ISSUE TITLE
Ruby Script Code Review

### ISSUE THREAD

**Issue by Lutzifer** [Swinject/Swinject-CodeGeneration#2]

**Comment by ddengler** [comment]
I can look into this, once you pushed the initial commit.

**Comment by yoichitgy** [comment]
@Lutzifer plz let me know when the code is ready for review.

**Comment by Lutzifer** [comment]
I would like to do #4 and #5 before.

**Comment by yoichitgy** [comment]
I created PR #24 as code review.

One thing I didn't change in the PR was naming convention. I think `snake_case` is preferred to `camelCase` for parameter and function names in Ruby. What is your idea about this naming convention?

**Comment by Lutzifer** [comment]
@ddengler you are the expert on that

**Comment by ddengler** [comment]
correct. snake_case is the preferred way. we should move the .rb files and .erb templates to one (or more) subfolders. currently everything lives in root.

**Comment by yoichitgy** [comment]
I agree. Especially utility scripts should be sorted into a subdirectory. E.g. README.erb and updateReadme.sh.

**Comment by Lutzifer** [comment]
I need to keep all the .rb files in the same folder, as I haven't found out yet whether i can include subfolders in pods. Thus, the pod has a flat hierarchy atm, which we need to mirror to use it in the examples.

Moving stuff into subfolders is great nonetheless.
