### ISSUE TITLE
Rename executable file and project?

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/Swinject-CodeGeneration#25]
**"CodeGen"** is a well-known short name for **"code generation"**. It looks good to rename our executable file and project to:
- Executable: `swinject_codegen`
- Project: `Swinject-CodeGen`

@Lutzifer: what do you think about the rename?

**Comment by Lutzifer** [comment]
will do

**Comment by yoichitgy** [comment]
Renamed the project in GitHub.

**Comment by yoichitgy** [comment]
@Lutzifer you also need to rename the forked project:
https://github.com/Lutzifer/Swinject-CodeGeneration

**Comment by Lutzifer** [comment]
fork wasnt needed anymore anyway
