### ISSUE TITLE
Use STDIN/STDOUT if -i/-o are not specified

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/Swinject-CodeGeneration#26]
The command line arguments look more natural to use `STDIN` and `STDOUT` if `-i` and `-o` are not passed as arguments, respectively.

**Comment by Lutzifer** [comment]
how should we handle different formats for stdin?

**Comment by yoichitgy** [comment]
That's a good point. I wasn't aware that. Adding another option to specify the file format solves this, but just making the options complicated.

So, requiring `-i` option is ok, and please ignore my idea to use `STDIN`.
