### ISSUE TITLE
Review of Generated Code

### ISSUE THREAD

**Issue by Lutzifer** [Swinject/Swinject-CodeGeneration#3]

**Comment by yoichitgy** [comment]
@Lutzifer plz let me know when the code is ready for review.

**Comment by Lutzifer** [comment]
This can be done, I do not have any open improvements/todos concerning the generated code atm

**Comment by yoichitgy** [comment]
I'll try reviewing in this weekend.

**Comment by yoichitgy** [comment]
Generated code has something like this:

``` swift
func resolveInjectablePerson() -> InjectablePerson {
    return self.resolve(PersonType.self)! as! InjectablePerson
}
```

I think we don't need `!` before `as!`. The generated code can be:

``` swift
func resolveInjectablePerson() -> InjectablePerson {
    return self.resolve(PersonType.self) as! InjectablePerson
}
```

**Comment by yoichitgy** [comment]
Generated code has something like this:

``` swift
func resolveInjectablePerson(foo: AType, bar: BType, baz: String, qux: String) -> InjectablePerson {
    return self.resolve(PersonType.self, arguments: (foo, bar, baz, qux))! as! InjectablePerson
}
```

I think it's more understandable if the first argument is labeled like this:

``` swift
func resolveInjectablePerson(foo foo: AType, bar: BType, baz: String, qux: String) -> InjectablePerson {
    return self.resolve(PersonType.self, arguments: (foo, bar, baz, qux))! as! InjectablePerson
}
```

Then you can use the function like this:

``` swift
let p = container.resolveInjectablePerson(foo: someFoo, bar: someBar, baz: "some baz", qux: "some qux")
```

**Comment by yoichitgy** [comment]
Generated code has something like this:

``` swift
extension Resolvable {
    func registerInjectablePerson(registerClosure: (resolver: ResolverType) -> (InjectablePerson)) -> ServiceEntry<PersonType> {
        return (self as! Container).register(PersonType.self, factory: registerClosure)
    }
}
```

It uses `(self as! Container)`, which expects the `Resolvable` instance must be `Container` type. I think it's more understandable to extend `Container` type for registration methods. (Resolution methods can stay in the extension of `Resolvable`.)

**Comment by yoichitgy** [comment]
I wrote three suggestions⬆️ What do you think about them?

**Comment by Lutzifer** [comment]
we had an issue with (self as! Container) in an earlier version of the code, but it seems to have vanished :-)

**Comment by yoichitgy** [comment]
@Lutzifer FYI: I'll rename `Resolvable` to `ResolverType` in Swinject 2.0.0.

https://github.com/Swinject/Swinject/pull/90
https://github.com/Swinject/Swinject/pull/87

CodeGen also needs migration to Swinject 2.0.0 later, but for now we can work on Swinject 1.x.

**Comment by Lutzifer** [comment]
we can bind the current version to swinject < 2.0.0, then update the generated code, release a new version and depend on swinject >= 2.0.0.
I do not see any necessary migrations, as the code will simply be replaced.
