### ISSUE TITLE
ADD_DEPENDENCY syntax

### ISSUE THREAD

**Issue by ddengler** [Swinject/Swinject-CodeGeneration#30]
@Lutzifer I would suggest to replace this with a simple comment block allowing any text to be placed as code in the resulting header instead of explicitly defining dependencies. This would be a lot more flexible. What do you think?

**Comment by yoichitgy** [comment]
@ddengler It's great to have the flexibility. On the other hand, limiting the option to ADD_DEPENDENCY makes the usage easier to understand. It's a trade off between flexibility and ease of use.

Would you give me examples for what you are going to use the flexibility?

(My opinion is still neutral. I want to know what kind of things can be achieved with the flexibility💪)

**Comment by ddengler** [comment]
@yoichitgy From the top of my head: preprocessor macros or some typedefs or whatever else a user might need in the header I cannot think of right now :)

**Comment by ddengler** [comment]
And a user does not have to learn the ADD_DEPENDENCY syntax and can just write / copy&paste what he is already used to

**Comment by yoichitgy** [comment]
@ddengler Thanks for the answers. Let me take time to think.
@Lutzifer What do you think?

**Comment by Lutzifer** [comment]
@ddengler @yoichitgy I would propose a general ADD_HEADER command. Simply using comments for it takes away the possibility to use comments for anything else.

**Comment by yoichitgy** [comment]
I think Lutzifer's idea ADD_HEADER is good.

@Lutzifer Do you mean we are going to support only ADD_HEADER? Or will you support ADD_DEPENDENCY too?

**Comment by Lutzifer** [comment]
I would only allow AD_HEADER, so 

`# ADD_DEPENDENCY Keychain`

becomes

`# ADD_HEADER import "Keychain"`

**Comment by yoichitgy** [comment]
@Lutzifer I agree, thanks for the clarification.

@ddengler What do you think about @Lutzifer's idea?

**Comment by Lutzifer** [comment]
the https://github.com/Swinject/Swinject-CodeGen/tree/example_add_header has a prototype implementation of this

**Comment by ddengler** [comment]
Rails uses in something like the following

`# some comment` for regular comments

`#= import "Keychain"` for code to be inserted

Basically the same but a lot shorter

**Comment by Lutzifer** [comment]
i like that

**Comment by yoichitgy** [comment]
So do I. Let's use `#=` to add a header part.

**Comment by Lutzifer** [comment]
fixed by #55
