### ISSUE TITLE
Use Pull Requests to Test Automatically before Merging into master

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/Swinject-CodeGeneration#32]
We've added tests to this project. Thanks @Lutzifer!

Now it's a very good practice to use Pull Requests to merge commits into master because the tests automatically run on Travis. You can keep master safe if you merge the Pull Requests after confirming the test results shown in the PRs.

It's ok to push a commit directly to master if it is a minor document update, but basically let's use PRs!

@Lutzifer plz close this issue if you got it😀

**Comment by yoichitgy** [comment]
Other advantages of PRs are:
- It's easy to see a group of related commits. 
- We can add comments to PRs.
- It's fun to see a green indicator of the tests🚥

**Comment by Lutzifer** [comment]
agreed, now that the changes are no longer that large, we can indeed use a PR workflow
