### ISSUE TITLE
mention CodeGen in Swinject Readme

### ISSUE THREAD

**Issue by Lutzifer** [Swinject/Swinject-CodeGeneration#57]
To gain some users, it would be nice if you mentioned CodeGen in the Readme of Swinject 😃

**Comment by yoichitgy** [comment]
OK! I will update it shortly 👍

**Comment by yoichitgy** [comment]
Add the mention about codegen in Swinject project ([#100](https://github.com/Swinject/Swinject/issues/100)). The PR got #100🎉
