### ISSUE TITLE
Leaving out component leads to wrong code

### ISSUE THREAD

**Issue by Lutzifer** [Swinject/Swinject-CodeGeneration#58]
`SomeType;SomeType;;a:String;b:String;c:String` yields correct results

while

`SomeType;;;a:String;b:String;c:String` is missing SomeType in the function name.

**Comment by yoichitgy** [comment]
Great👍

By the way, [the CI failed on this pull request](https://travis-ci.org/Swinject/Swinject-CodeGen/jobs/130368328). It's a good practice to merge a pull request after checking its CI passes.
