### ISSUE TITLE
Add a description to the project

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/Swinject-CodeGeneration#60]
@Lutzifer, would you add a nice description to the project?

<img width="347" alt="screen" src="https://cloud.githubusercontent.com/assets/965994/15362977/0880587c-1d52-11e6-900f-778c61a72834.png">

**Comment by Lutzifer** [comment]
Proposing "Generate code to make the use of Swinject type-safe and reduce duplicate identifiers for Services"

I cannot edit it though.

**Comment by yoichitgy** [comment]
Thanks @Lutzifer for your idea for the description. I updated it as you wrote. 

(I had misunderstanding you could update it with your Maintainer's right.)
