### ISSUE TITLE
How to test this?

### ISSUE THREAD

**Issue by Lutzifer** [Swinject/Swinject-CodeGeneration#8]
we should add test cases to this, what would be a good way of specifying them in this case?

**Comment by ddengler** [comment]
Travis (osx machine) + ruby minitest for the basic script? Rspec is probably overkill.
Plus some xcode testing project to make sure generated code compiles properly and is compatible to the specified Swinject version?

**Comment by yoichitgy** [comment]
I agree with @ddengler's idea. Simple test in Ruby, and build test with generated code in Xcode.

I enabled Travis for Swinject-CodeGeneration
https://travis-ci.org/Swinject/Swinject-CodeGeneration

**Comment by yoichitgy** [comment]
In the test, we should use 2 versions of Ruby:
- The latest stable version
- The version bundled with El Capitan

**Comment by Lutzifer** [comment]
~~@yoichitgy travis does no longer find the repo due to rename~~
Ignore what i wrote...

**Comment by Lutzifer** [comment]
added a simple build test using fastlane and scan

**Comment by yoichitgy** [comment]
fastlane🎉
