### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by Lutzifer** [Swinject/Swinject-CodeGeneration#9]

**Comment by ddengler** [comment]
should fit into the readme from my point of view

**Comment by yoichitgy** [comment]
Adding documentation is great👍 At the beginning, we use README. After the README gets larger, I prefer using `Documentation` directory in the repo without using Wiki like Swinject project does.

https://github.com/Swinject/Swinject/tree/master/Documentation

In this way, anyone can send pull requests to documentation. (GitHub Wiki does not support PR.)

**Comment by yoichitgy** [comment]
I'm going to turn off Wiki.

**Comment by yoichitgy** [comment]
We also need to update [Swinject's README](https://github.com/Swinject/Swinject/blob/master/README.md) to link this project.

**Comment by Lutzifer** [comment]
For the time being, adapted the Proposal for the Readme
